{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "springcontroller.serviceAccountName" . }}
  labels:
{{ include "springcontroller.labels" . | nindent 4 }}
{{- end -}}
